//
// Generated file, do not edit! Created by nedtool 4.6 from src/CloudCongestionUpdate.msg.
//

#ifndef _CLOUDMGN_CLOUDCONGESTIONUPDATE_M_H_
#define _CLOUDMGN_CLOUDCONGESTIONUPDATE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace cloudMGn {

/**
 * Class generated from <tt>src/CloudCongestionUpdate.msg:18</tt> by nedtool.
 * <pre>
 * //
 * // CloudCongestionUpdate message definition for M/G/n simulations
 * //
 * message CloudCongestionUpdate
 * {
 *     //@customize(true);
 *     bool congestion;			// Congestion status: true or false
 *     double multiplier;			// multiplier for service/delay time
 * }
 * </pre>
 */
class CloudCongestionUpdate : public ::cMessage
{
  protected:
    bool congestion_var;
    double multiplier_var;

  private:
    void copy(const CloudCongestionUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CloudCongestionUpdate&);

  public:
    CloudCongestionUpdate(const char *name=NULL, int kind=0);
    CloudCongestionUpdate(const CloudCongestionUpdate& other);
    virtual ~CloudCongestionUpdate();
    CloudCongestionUpdate& operator=(const CloudCongestionUpdate& other);
    virtual CloudCongestionUpdate *dup() const {return new CloudCongestionUpdate(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getCongestion() const;
    virtual void setCongestion(bool congestion);
    virtual double getMultiplier() const;
    virtual void setMultiplier(double multiplier);
};

inline void doPacking(cCommBuffer *b, CloudCongestionUpdate& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CloudCongestionUpdate& obj) {obj.parsimUnpack(b);}

} // namespace cloudMGn

#endif // ifndef _CLOUDMGN_CLOUDCONGESTIONUPDATE_M_H_

